### PR TITLE
Add C-accelerated code

### LINKED ISSUE #38: Use either pytest or unittest, not both
Currently everything in algorithm/ uses pytest for testing while everything in fqe_ops/ uses unittest. Is there a reason for using both? AFAIK it's standard to only use one.

### LINKED ISSUE #50: Add tests for FciGraphSet
Currently only one simple test in https://github.com/quantumlib/OpenFermion-FQE/blob/master/src/fqe/fci_graph_set_test.py

### LINKED ISSUE #51: Lingering todo in FqeData
Has this [todo](https://github.com/quantumlib/OpenFermion-FQE/blob/master/src/fqe/fqe_data.py#L1004) in FqeData been resolved?

### LINKED ISSUE #55: Add tests to FQE control
Coverage is pretty low in [_fqe_control_test.py](https://github.com/quantumlib/OpenFermion-FQE/blob/master/src/fqe/_fqe_control_test.py). 

I haven't gone through everything yet, but it seems like getter methods which just wrap class constructors in _fqe_control.py, e.g. https://github.com/quantumlib/OpenFermion-FQE/blob/master/src/fqe/_fqe_control.py#L392, could be removed as an alternative to increasing coverage.

### PR DESCRIPTION
**Pull request by awhite862**
Edit by TS: This merge will
- resolve #38 
- resolve #50 
- resolve #51 
- resolve #55

### CODE REVIEW

**Review by ncrubin — COMMENTED** [review]
do we need to update the requirements to include Cython?

**Comment by shiozaki** [comment]
Yes, we do need Cython to compile. We've just had an internal chat - Alec will address the merge issues shortly.

**Comment by awhite862** [comment]
Yes, I'm working on fixing the the formatting errors. I also need to update the github CI so that it actually builds the package

**Comment by awhite862** [comment]
@googlebot I signed it!

**Comment by shiozaki** [comment]
@googlebot I consent

**Comment by klgunst** [comment]
@googlebot I consent

**Pull request merged**
