### PR TITLE
Call normalize in set_wfn when strategy is random

### LINKED ISSUE #82: when initializing wf with multiple sectors normalize before returning
Wavefunctions initialized over multiple sectors are nor normalized.

```
wfn_fqe = fqe.Wavefunction([[2, 0, 4], [2, -2, 4]], broken=None)
wfn_fqe.set_wfn(strategy="random")
wfn_fqe.print_wfn()
wfn.norm()  # this should be 1
```
This can be fixed by calling `self.normalize()` before returning from the initialization function.

### PR DESCRIPTION
**Pull request by rmlarose**
Fixes #82.

### CODE REVIEW

**Comment by shiozaki** [comment]
Hi Ryan - thanks for taking care of this! One thing - if you are to normalize in wavefunction (which is the right thing to do), could you remove the normalization in util. rand_wfn https://github.com/quantumlib/OpenFermion-FQE/blob/master/src/fqe/util.py#L429 

Normalization in rand_wfn would make random initialization not really random (sectors will be scaled differently).

**Comment by rmlarose** [comment]
Thanks @shiozaki!

> could you remove the normalization in util. rand_wfn https://github.com/quantumlib/OpenFermion-FQE/blob/master/src/fqe/util.py#L429

> Normalization in rand_wfn would make random initialization not really random (sectors will be scaled differently).

Ah! Thanks for pointing this out, will do.

> PS: also if you could clean up the comment in that function, I'd appreciate it. Not sure how this happened... sorry.

I'll format the docstring of `set_wfn` as well, no worries!

**Review by shiozaki — APPROVED** [review]
I've added a minor change in the code documentation, but otherwise, the changes look good to me. Contingent on Nick's approval this can be merged.

**Comment by shiozaki** [comment]
@googlebot I consent.

**Review by ncrubin — APPROVED** [review]

**Pull request merged**
