### PR TITLE
add Cython to requirements

### PR DESCRIPTION
**Pull request by ncrubin**

### CODE REVIEW

**Comment by shiozaki** [comment]
@ncrubin cython has to be installed before setup.py is called (because cythonize is imported at the beginning of the setup.py). I am not an expert but it appears to me that the best practice is to use pyproject.toml ?
https://stackoverflow.com/questions/55598951/how-to-make-cython-a-requirement-for-a-pip-install

**Comment by ncrubin** [comment]
@shiozaki pyproject.toml is now used to specify to pip that Cython numpy and scipy are required for the build.  numpy and scipy are required because scipy.linalg.cython_blas is needed (I think).  I've also updated the mypy to a newer version because I was getting gcc build issues with typed-ast.  typing is removed from requirements.  This is in standard lib now I think.  @awhite862 or @klgunst should confirm these changes.

**Comment by klgunst** [comment]
@ncrubin The changes seem good to me! @awhite862 is out of office atm.

**Comment by ncrubin** [comment]
I should have tested if build works (which it currently does not). which means no new release.  I won't roll back this commit but untag the release.

**Pull request merged**
